server:
  port: 8086
  servlet:
    context-path: /evaluation-service

spring:
  application:
    name: evaluation-service
  datasource:
    url: jdbc:mysql://localhost:3306/egov_evaluation?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: evaluation-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: "com.egov.tendering.*"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 60000
        loggerLevel: full
  circuitbreaker:
    enabled: true
  compression:
    request:
      enabled: true
    response:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always

# Custom application properties
app:
  kafka:
    topics:
      evaluation-created: evaluation-created
      evaluation-updated: evaluation-updated
      evaluation-status-changed: evaluation-status-changed
      evaluation-deleted: evaluation-deleted
      tender-evaluation-completed: tender-evaluation-completed
      tender-evaluation-approved: tender-evaluation-approved
      review-created: review-created
      review-updated: review-updated
      review-deleted: review-deleted
  feign:
    tender-service: tender-service
    bid-service: bidding-service
    user-service: user-service